apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: projeto-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    # Como o ArgoCD usa HTTPS internamente, esta anotação ajuda a evitar erros de redirecionamento
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules:
  - host: argo.150.230.172.200.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: argocd-server
            port:
              number: 443
  - host: moedas.150.230.172.200.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: collector-service
            port:
              number: 80
